### ISSUE TITLE
vuefes-2019 リポジトリのソースコードを公開する

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/vuefes-2019#201]
@kazupon @448jp @ryamakuchi @yinm @aytdm 

## 解決したい問題

vuefes-2019 リポジトリのソースコードには知見が溜まっていると思われるが、現在 Private リポジトリであるため、Vue Fes コアスタッフしか閲覧することができない。

## 問題を解決するために

`kazupon/vuefes-2019` リポジトリを `vuejs-jp/vuefes-2019` へ移行させる。

ref: https://github.com/kazupon/vuefes/issues/378#issuecomment-472712216

## この Issue の完了条件

- [x] 移行して問題がある情報などが編集または削除されること by @inouetakuya
- [x] `kazupon/vuefes-2019` リポジトリが `vuejs-jp/vuefes-2019` へ移行される by @kazupon
- [x] 必要に応じて Netlify の設定変更 by @kazupon 
- [x] Netlify でビルドできるか確認する by @kazupon 

## 期限

vuefes-2019 リポジトリで用いた技術を解説する記事を、アドベントカレンダーの記事として書く予定です。

12/18（水）までに公開したいです。

**Comment by kazupon** [comment]
vuejs-jp に移管しました。

**Comment by kazupon** [comment]
@inouetakuya 
netlifyの設定変更も終わり、ビルドできること確認できました！

**Comment by inouetakuya** [comment]
最高です！ありがとうございます！予定していたことが完了したので Issue クローズします！:tada:
